version: '3.8'

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - C_FORCE_ROOT=true
    command: celery -A app.worker worker --loglevel=info
    depends_on:
      - redis

  beat:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - celerybeat:/var/run/celery
    env_file:
      - ./backend/.env
    environment:
      - C_FORCE_ROOT=true
    command: celery -A app.worker beat --loglevel=info --schedule=/var/run/celery/celerybeat-schedule
    depends_on:
      - redis

volumes:
  redis_data:
  celerybeat:
