"""initial

Revision ID: 855df3f183f2
Revises: 
Create Date: 2025-01-29 00:16:22.350710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855df3f183f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FEDERAL', 'STATE', 'EXECUTIVE', name='legislationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'PASSED', 'FAILED', 'SIGNED', 'VETOED', name='status'), server_default='PENDING', nullable=False),
    sa.Column('introduced_date', sa.DateTime(), nullable=True),
    sa.Column('last_action_date', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legislative_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('legislation_id', sa.String(), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legislative_actions')
    op.drop_table('legislation')
    # ### end Alembic commands ###
